/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

        @Test
    public void testFound() {
        //toplam arr mevcut
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4,5));
        assertTrue(App.isSumInArray(arr, 0, 0, 1));
    }

    @Test
    public void testFound1() {
        //toplam arr mevcut
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4,5));
        assertTrue(App.isSumInArray(arr, 0, 1, 1));
    }
    @Test
    public void testFound2() {
        //toplam arr mevcut
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4,5));
        assertTrue(App.isSumInArray(arr, 1, 1, 1));
    }
    @Test
    public void testNotFound() {
        //toplam arr mevcut değil
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4,5));
        assertFalse(App.isSumInArray(arr, 0, 0, 0));
    }

    @Test
    public void testFoundNegativeX() {
        //toplam arr mevcut fakat negatif x
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4,5));
        assertFalse(App.isSumInArray(arr, -1, 0, 3));
    }
    
    @Test
    public void testFoundNegativeY() {
        //toplam arr mevcut fakat negatif x
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4,5));
        assertFalse(App.isSumInArray(arr, 0, -1, 3));
    }

    @Test
    public void testFoundNegativeZ() {
        //toplam arr mevcut fakat negatif z
        ArrayList<Integer> arr = new ArrayList<>(Arrays.asList(1,2,3,4,5));
        assertFalse(App.isSumInArray(arr, 3, 0, -2));
    }

    @Test
    public void testNullArray() {
        //arr is null
        ArrayList<Integer> arr = null;
        assertFalse(App.isSumInArray(arr, -1, 0, 3));
    }
    @Test
    public void testEmptyArray() {
        //arr is empty
        ArrayList<Integer> arr = new ArrayList<>();
        assertFalse(App.isSumInArray(arr, -1, 0, 3));
    }
}
