/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean isSumInArray(ArrayList<Integer> arr, int x, int y, int z) {
        //not negative nums
        if (arr == null || x < 0 || y < 0 || z < 0) return false;
        if (arr.size() <= 0) return false;
        int sum = x + y + z;
        
        //if (sum < 0) return false; //yukarda kontrol ettik 

        for (Integer value : arr) {
            if (value == sum) {
                return true;
            }
        }
        return false;
    }  
}   
